# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0002_auto_20161130_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('statu', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'userWeb_userList',
                'verbose_name_plural': 'user_list',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('info', 'info'), ('danger', 'danger')], max_length=20, null=True, verbose_name='\u6587\u7ae0\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 19, 31, 42, 277604)),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 19, 31, 42, 277528)),
        ),
    ]
