# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radiusUser', '0002_radacct_radcheck_radgroupcheck_radgroupreply_radippool_radpostauth_radreply_radusergroup_realmgroup_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radusergroup',
            name='updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
