# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusUser', '0003_auto_20161103_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radusergroup',
            options={'verbose_name_plural': 'radusergroup'},
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 16, 13, 59, 568568)),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 16, 13, 59, 568487)),
        ),
    ]
