# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusUser', '0004_auto_20161130_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radusergroup',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 3, 19, 31, 42, 256226)),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 2, 19, 31, 42, 256133)),
        ),
    ]
