# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=253)),
                ('secret', models.CharField(max_length=253)),
                ('groupname', models.CharField(max_length=64)),
                ('ips_now', models.IntegerField()),
                ('ips_limits', models.CharField(max_length=253)),
                ('traffic_now', models.IntegerField()),
                ('traffic_limits', models.CharField(max_length=253)),
                ('speed_limits', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'showing',
                'managed': False,
                'verbose_name_plural': 'showing',
            },
        ),
        migrations.RemoveField(
            model_name='nas',
            name='coasecret',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='naslocation',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='snmp',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='vhost',
        ),
        migrations.RemoveField(
            model_name='radacct',
            name='acctstartdelay',
        ),
        migrations.RemoveField(
            model_name='radacct',
            name='acctstopdelay',
        ),
        migrations.RemoveField(
            model_name='radacct',
            name='xascendsessionsvrkey',
        ),
        migrations.RemoveField(
            model_name='radpostauth',
            name='calledstationid',
        ),
        migrations.RemoveField(
            model_name='radpostauth',
            name='callingstationid',
        ),
        migrations.RemoveField(
            model_name='radreply',
            name='calledstationid',
        ),
        migrations.RemoveField(
            model_name='radreply',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='radusergroup',
            name='calledstationid',
        ),
        migrations.AddField(
            model_name='nas',
            name='description',
            field=models.CharField(blank=True, default='RADIUS Client', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nas',
            name='server',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='radacct',
            name='acctinterval',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='radusergroup',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='radacct',
            name='acctsessionid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='radreply',
            name='attribute',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='radreply',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='radreply',
            name='value',
            field=models.CharField(max_length=253),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='groupname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='radusergroup',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
