# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRad', '0003_auto_20161031_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showing',
            options={'managed': False, 'verbose_name_plural': 'view_showing'},
        ),
        migrations.AlterField(
            model_name='radcheck',
            name='attribute',
            field=models.CharField(default='Cleartext-Password', max_length=64),
        ),
        migrations.AlterField(
            model_name='radcheck',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('==', '=='), ('+=', '+='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default=':=', max_length=2),
        ),
        migrations.AlterModelTable(
            name='showing',
            table='view_showing',
        ),
    ]
