# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testRad', '0004_auto_20161101_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='radusergroup',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='radusergroup',
            name='updatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
