# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testRad', '0005_auto_20161101_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radusergroup',
            old_name='enddate',
            new_name='endtime',
        ),
    ]
