# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusServer', '0002_nas_nasattributes_nasshowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasattributes',
            name='vps_endtime',
            field=models.DateField(),
        ),
    ]
